create table if not exists public.workspaces (
  id integer generated by default as identity primary key,
  name varchar(80) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.todos (
  id integer generated by default as identity primary key,
  title varchar(200) not null,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  workspace_id integer not null references public.workspaces(id) on delete cascade
);

create index if not exists todos_workspace_id_created_at_index
  on public.todos (workspace_id, created_at);

insert into public.workspaces (name, created_at, updated_at)
select 'My workspace', now(), now()
where not exists (select 1 from public.workspaces);
